---
title: "R code snippet"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## 一、数据读取
### 读入csv格式，观测多少行，观测多列以及列名
```{r}
vehicles <- read.csv("vehicles.csv")
head(vehicles)
nrow(vehicles)
ncol(vehicles)
names(vehicles)
```
### 数据导入与导出
```{r}
library(readr)
couts <- read_csv("~/Desktop/couts.csv")
write.csv(couts,"~/zjif.csv")
```

#### 取sample
```{r}
set.seed(20022012)
diamond_samp <- diamonds[sample(1:length(diamonds$price), 10000), ]

sample（x, size, replace = FALSE）

#参数 说明
#x 整体数据，以向量形式给出
#size 抽取样本的数目
#replace 如果为F（默认），则是不重复抽样，此时size不能大于x的长度；
#如果为T，则是重复抽样，此时size允许大于x的长度

```

### 取一列不同的值，确定不同的值数量，确定同列中最大值最小值
```{r}
length(unique(vehicles$year))
unique(vehicles$year)
max(vehicles$year)
min(vehicles$year)
```
### 缺失值用NA填补
```{r}
vehicles$trany[vehicles$trany == ""] <- NA
```

### 缺失值NA全部替换为0
```{r}
tongdun3[is.na(tongdun3)] <- 0
```

### 将变量变成因子，使用table函数观察变量不同取值所对应的记录数
```{r}
vehicles$trany <- as.factor(vehicles$trany)
table(vehicles$trany)
```
### 将变量变成数值型
```{r}
gasCars$displ <- as.numeric(gasCars$displ)
```
### 观察变量类型，以及都有哪些值
```{r}
class(vehicles$sCharger)
unique(vehicles$sCharger)
```
### 数据筛选
```{r}
library(dplyr)
library(xlsx)
library(rJava)
df <- filter(tongdun3, (tongdun3$`24个月内多个平台申请数` > 100 & tongdun3$`12个月内多个平台申请数` > 100) | (tongdun3$`3个月内多个平台申请数` > 20 & tongdun3$身份证命中犯罪通缉名单  == "命中"))
summary(df)
```

### 修改列名
```{r}
colnames(df)=c("Mary","Alice","Bob","Judy","jason")
```
### 缺失值标记
```{r}
library(Amelia)
missmap(df)
```



### ggplot画图，并生成平滑曲线
```{r}
ggplot(mpgByYr,aes(year,avgMPG))+geom_point()+geom_smooth()
```
### ggplot画图，并生成分面图形
```{r}
ggplot(mpgByYr,aes(year,avgMPG))+geom_point()+facet_wrap(~make,nrow=3)
```

### ggplot ggpairs 函数
#### ggscatmat 函数
```{r}
library(GGally)
#ggscatmat(trees)
data("iris")
ggscatmat(iris, columns = 1:4,color = 'Species' )
```

#### ggpairs函数
```{r}
library(ggplot2)
library(GGally)
data(tips,package="reshape")
#pairs(tips[,1:3])
pm1 <- ggpairs(
tips[,c(1,3,4,2)],
mapping = ggplot2::aes(color = sex,shape=sex,alpha = 0.4),
upper = list(continuous = "cor", combo = "box", discrete = "facetbar"),
lower = list(continuous = "points", combo = "facethist", discrete = "facetbar"),
diag = list(continuous = "densityDiag", discrete = "barDiag")
)
pm1


data(iris)
pm2 <- ggpairs(
iris[,c(1,2,5,3,4)],
mapping = ggplot2::aes(color = Species,shape=Species,alpha = 0.4),
upper = list(continuous = "density", combo = "box"),
lower = list(continuous = "points", combo = "dot"),
title = "Iris",
axisLabels ="internal")
pm2


diamonds.samp <- diamonds[sample(1:dim(diamonds)[1], 200), ]
# Custom Example
pm3 <- ggpairs(
diamonds.samp[, 1:5],
mapping = ggplot2::aes(color = cut),
upper = list(continuous = wrap("density", alpha = 0.5), combo = "box"),
lower = list(continuous = wrap("smooth", alpha = 0.3), combo = wrap("dot", alpha = 0.4)),
title = "Diamonds"
)
pm3
```


### 随机森林算法randomForest
```{r}
作者：周小生
链接：https://zhuanlan.zhihu.com/p/27044470
来源：知乎
著作权归作者所有，转载请联系作者获得授权。

install.packages("randomForest")
  library(randomForest)
   
  # 下载泰坦尼克号幸存者数据集
  data <- read.table("http://math.ucdenver.edu/RTutorial/titanic.txt", h=T, sep="\t")
  # 将Survived列转为yes/no因子
  data$Survived <- as.factor(ifelse(data$Survived==1, "yes", "no"))              
   
  # 拆分为训练集和测试集
  idx <- runif(nrow(data)) <= .75
  data.train <- data[idx,]
  data.test <- data[-idx,]
   
  # 训练一个随机森林
  rf <- randomForest(Survived ~ PClass + Age + Sex,
               data=data.train, importance=TRUE, na.action=na.omit)
   
  # 模型中每个变量的重要程度
  imp <- importance(rf)
  o <- order(imp[,3], decreasing=T)
  imp[o,]
  #             no      yes MeanDecreaseAccuracy MeanDecreaseGini
  #Sex    51.49855 53.30255             55.13458         63.46861
  #PClass 25.48715 24.12522             28.43298         22.31789
  #Age    20.08571 14.07954             24.64607         19.57423
   
  # 混淆矩阵 [[真反例, 假正例], [假反例, 正正例]]
  table(data.test$Survived, predict(rf, data.test), dnn=list("actual", "predicted"))
  #      predicted
  #actual  no yes
  #   no  427  16
  #   yes 117 195
```






